# Training parameters
training:
  dataset_percentage: 0.02  # Percentage of dataset to use (2%)
  batch_size: 32
  epochs: 5
  validation_split: 0.2
  learning_rate: 0.001

# Model parameters
model:
  dropout_rate: 0.3
  conv_filters: [32, 64, 128]
  dense_units: [256, 128]

# Feature extraction parameters
features:
  # Basic parameters
  sample_rate: 16000
  fixed_time_steps: 128
  fixed_freq_bins: 128
  
  # MFCC parameters
  n_mfcc: 20
  n_mels: 128
  
  # Spectrogram parameters
  n_fft: 2048
  hop_length: 512
  win_length: 2048
  window: 'hann'
  
  # Additional features
  spectral_features:
    - 'spectral_centroid'
    - 'spectral_bandwidth'
    - 'spectral_rolloff'
    - 'spectral_flatness'
    - 'zero_crossing_rate'
  
  # Chroma parameters
  n_chroma: 12
  
  # Tempogram parameters
  tempo_hop_length: 256
  
  # Onset detection parameters
  onset_hop_length: 512
  onset_backtrack: true
  
  # Normalization
  normalize_features: true
  normalization_range: [-1, 1]

# Paths
paths:
  evaluation_dir: "./evaluation"
  models_dir: "./models" 